### ISSUE TITLE
Thank you for your work, it's great. But I still want to ask why there is no YeNet and SRNet, these are very representative results.

### ISSUE THREAD

**Issue by BlueQWQ** [totohoon01/steganalysis#1]

**Comment by totohoon01** [comment]
sorry, I'm not familiar with github, I just noticed your comment.
I tried some structures like xu, resnet, pelee etc, in my results, I preferred reset and pelee net.
I didn't tried SRNET and YeNet,  I will consider about them.
Thanks anyway.
